# This file was generated by GoReleaser. DO NOT EDIT.
cask "homeport" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "9528926957b521287683ddf2b00d3a71e4eb589e3e959e0c751368eefa32d89e"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c8eba371ef8c05063b43a19ed145a6c9289ceeb6c7e53633a126e0296512596c"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "003a4308e6a3273ea9bd42a9125d7b6edaf818af346621e00c5472715b505a1d"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c67f336898d1f80efa866d0bd8d2251e2776d2b9759398e9c4b84117a7a9dfaa"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homeport"
  desc "Deploy single-binary web apps to your own VPS — no Docker, no registry, no runtime on the server."
  homepage "https://homeport.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homeport"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homeport"]
    end
  end

  # No zap stanza required
end
