# This file was generated by GoReleaser. DO NOT EDIT.
cask "homeport" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "a3f39b1234a0d5f7f4102f91c7d6461806cc0372046b2dd0a2a9317c18fdd9c0"
      url "https://github.com/homeport-sh/cli/releases/download/v#{version}/homeport_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a2a933087dc2465e47e9ffe898b6b75db06b288817fb041725e134fbbc8b533"
      url "https://github.com/homeport-sh/cli/releases/download/v#{version}/homeport_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25158b7e37d016055963932928587c0052b0cd1251f0e0100aa46aea71e7a016"
      url "https://github.com/homeport-sh/cli/releases/download/v#{version}/homeport_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "829f93b5bfb0ec2fd52d8bd57f7836ec24a723238883fc5d6970a35c063c8a77"
      url "https://github.com/homeport-sh/cli/releases/download/v#{version}/homeport_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homeport"
  desc "The command-line tool for homeport, the hosted platform for single-binary and static apps."
  homepage "https://homeport.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homeport"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homeport"]
    end
  end

  # No zap stanza required
end
