# This file was generated by GoReleaser. DO NOT EDIT.
cask "homeport" do
  version "0.5.15"

  on_macos do
    on_arm do
      sha256 "9e67486cc5fefb9da7d280f0b91f554eecf65df41f4c524512f3e7689d8c85bb"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07e38a87de8622456dbcfe96a0c4787e9d726ab17388eb5bdfcd15a6e7309978"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0824e42499b5393cf86dab6abd551ca68d982a04011220abf8abd9bff40914f1"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de00246293cfd99e305fd97be78b0d6896466c59ba0ebe183b1f559bf6d3c059"
      url "https://github.com/homeport-sh/homeport/releases/download/v#{version}/homeport_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homeport"
  desc "Deploy single-binary web apps to your own VPS — no Docker, no registry, no runtime on the server."
  homepage "https://homeport.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homeport"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homeport"]
    end
  end

  # No zap stanza required
end
